### PR TITLE
Version 6.0.0

### LINKED ISSUE #1029: Refactor start screen
There has been much feedback that the current start screen is not ideal for users. The plan for this is to replace the current start screen with a sortable and filterable `CardList` with the default sort option being by most recently installed.

### LINKED ISSUE #1031: Drag and Drop Performance issues
In the development protocol on the CSV name generator, when starting a to drag a node there is a console warning about the event handler duration. It only fires when the drag first starts, and there is a very visible hitch from the user perspective at the same time. It kind of ruins the 'feel' of dragging.

It seems like the issue is that when a drag start is detected, a redux action is dispatched (`DRAG_START`) which takes 150ms to execute. This only fires once, and right at the start, but it is enough to hitch the animation and ruin the UX. Temporarily commenting this out makes performance buttery smooth.

We believe this is causing some unnecessary re-rendering. To investigate further we need to to rendering profiling of the component tree.

### LINKED ISSUE #1034: sessions list filter error
When typing in the filter field for the sessions list on the start screen, sometimes this error occurs:

```
TypeError: Cannot read property 'toString' of null
(anonymous function)
C:/Users/Big Baloo/Documents/GitHub/NetworkCanvas/src/components/FilterableListWrapper.js:56
  53 |   const nodeDetails = Object.values(node[entityAttributesProperty]);
  54 |   // Include in filtered list if any of the attribute property values
  55 |   // include the filter value
> 56 |   return nodeDetails.some(
     | ^  57 |     item => item.toString().toLowerCase().includes(filterValue),
  58 |   );
  59 | },
```

`item` is sometimes `null`, hence the error.

### LINKED ISSUE #1055: Update react-redux for hooks support
Version 7 of react-redux includes hooks for state and action dispatches, which would allow us to use custom React hooks without needed to pass dispatch/state as arguments. e.g.

```jsx
const useCustomHook = (dispatch, someStateFromStore) => {
  const doThing =  (v) => dispatch({ type: 'DO_THING', payload: v });
  const modifiedValue = someStateFromStore * 10;
  
  return [modifiedValue, doThing];
};

const MyComponent = ({ dispatch, someStateFromStore }) => {
  const [value, doThing] = useCustomHook(dispatch, someStateFromStore);

  return <div>{value}<div>;
};

connect(mapStateToProps)(MyComponent);
```

Could simplified to:

```jsx
const useCustomHook = () => {
  const someStateFromStore = useSelector(selectorReturningObject, shallowEqual);
  const doThing =  (v) => dispatch({ type: 'DO_THING', payload: v });
  const modifiedValue = someStateFromStore * 10;
  
  return [modifiedValue, doThing];
};

// Much tidier component:
const MyComponent = () => {
  const [value, doThing] = useCustomHook();

  return <div>{value}<div>;
};
```

As of writing best candidate would be:
react-redux 7.2

This would require:
react 16.8.3 or later

We could also update redux to version 4.x.x although this is not a requirement.

### LINKED ISSUE #1067: ready to upload to server message incomplete
The message on the "ready to export" dialog trails off as incomplete. My screen shows "Ready to export 1 session to ." It's expecting the paired server to have a `name`, but I don't have a name for my paired server. Should we be using the ip address instead? Or is the paired server supposed to have a name?

uploadmessage

### PR DESCRIPTION
**Pull request by jthrilly**
Obviously this PR is pretty substantial, and I don't expect that it can be reviewed in minute detail. Instead I would like you to focus on the core functionality, and to check that the essential functions of the application are working for you. We will deal with bugs in future PRs.

## Changes:

- Introduces substantially redesigned card-based start screen (Resolves #1029) including sections for common actions. All sections should be sensitive to app state and device state, meaning that they will contextually show themselves when their action is possible, and will disable subsets of their actions according to device network state/server pairing state.
- Adds a "preloading" animation that lets the app transition into the start screen view nicely on first launch.
- Adds a "welcome section" that can be optionally shown/hidden (default is shown on first launch) containing links to documentation.
- In preparation for stable, bumps the app version to 6.0.0 all app bundles and local storage keys to a new identifier.
- Removes compatibility with schema versions prior to 4, since this will be the launch schema version.
- A new `useServerConnectionStatus` hook has been written, which allows components to poll for heartbeat messages from server (not currently implemented).
- The flow for pairing with Server and fetching protocols has been redesigned and largely re-written on the component level. Pairing takes places from a dedicated Server communication card, and fetching protocols happens from a dedicated protocol import/management card. Resolves #1067. 
- A toast UI system has been written and implemented for protocol import, protocol export, and server pairing success.
- The display of protocol cards, session cards, and cards representing a computer running Server have been standardised within NC-UI and implemented here.
- Refactors import and export behaviour to not use redux state, but instead to dispatch toast actions.
- Redesigns the finish interview screen to remove delete session and export options. Includes a `finishedAt` session property, as well as in-session duration information.
- Fixes incorrect windows file menu items.
- Implements the ability to have custom validation functions passed to a field and through a form config object. These validation functions can contain custom reject messages.
- Removes obsolete cruft related to react-router, and implements latest libraries. Fixes #1055 
- Updates redux and redux-persist.
- Changes the app frame on windows to show the menu bar, and changes the startup behaviour to windowed. Full screen option is still available, but ive seen too many people be confused by it.
- Resolves #1034 
- Resolves #1031 (and helps with #1066) by successfully throttling dispatch of actions that update node position while dragging
- Changes drag manager portalling to the body element to help with z-index issues.
- Removes the `selectable` behaaviour in favour of components binding their own events and managing props of children.
- Implements a new filtered list wrapper for start screen items, and preserves the old one for use in the interview.
- Implements an `<ExternalLink />` component and an `openExternalLink` method to allow documentation links to be opened from within the app.
- Removes the development protocol as a submodule. As far as I could tell it wasn't being used.

### CODE REVIEW

**Comment by jthrilly** [comment]
- [ ] Pressing "tab" while the toggle show welcome message switch is active makes the panel vanish!

Kate's feedback:

- [ ] Don't show "compelete" toast when export was cancelled

**Comment by rebeccamadsen** [comment]
Looks pretty great! I can add one more observation. The date field does some funky things with aligning here, which isn't in master.

date

**Comment by jthrilly** [comment]
Update:

- I can't see anything wrong with the server protocol fetch dialog that would cause that wonky rendering, but I saw it a single time too. I've updated framer-motion, and I haven't seen it yet so we will just have to see if we can get a firm reproduction.
- Date picker bug was resolved in UI
- I'm going to leave the "complete" toast for now - I think its consistent with the pattern.
- I can't fix the tab issue. Leaving it for now

**Comment by jthrilly** [comment]
Outstanding iOS issues:

- [ ] Server discovery is broken
- [ ] New case form doesn't let you type into it
- [ ] Timeline navigation invisible
- [ ] Ego form progress bar too close to bottom of the screen
- [ ] Import from file doesn't trigger file chooser
- [ ] Forms push content off screen (regression)
- [ ] Header background gradient renders incorrectly

**Review by wwqrd — APPROVED** [review]

**Pull request merged**
